include: package:amplify_lints/library.yaml

analyzer:
  errors:
    implementation_imports: error      
  exclude:
    - lib/**/*.g.dart
    - lib/src/sdk/src/**
    - lib/src/native_auth_plugin.dart
